server:
  port: 4004

spring:
  cloud:
    gateway:
      routes:
        - id: vehicle-service-route
          uri: http://vehicle-service:4000
          predicates:
            - Path=/api/vehicles/**
          filters:
            - StripPrefix=1

        - id: api-docs-vehicle-route
          uri: http://vehicle-service:4000
          predicates:
            - Path=/api-docs/vehicles
          filters:
            - RewritePath=/api-docs/vehicles,/v3/api-docs